# Generated by Django 5.1.4 on 2025-01-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='quantity',
            new_name='quantity_in_stock',
        ),
        migrations.AddField(
            model_name='inventory',
            name='quantity_sold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
