# Generated by Django 5.1.2 on 2025-01-04 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_inventory_sales'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_sold',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
