# Generated by Django 5.1.2 on 2025-01-04 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_quantity_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='sales',
            field=models.DecimalField(decimal_places=2, max_digits=19),
        ),
    ]
