# Generated by Django 5.1.4 on 2025-01-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_quantity_inventory_quantity_in_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='total_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
