# Generated by Django 5.1.4 on 2025-01-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_inventory_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_sold',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='total_quantity',
            field=models.PositiveIntegerField(default=3),
            preserve_default=False,
        ),
    ]
