# Generated by Django 5.1.4 on 2025-01-07 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_inventory_quantity_in_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='quantity_sold',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
